version: "3.7"

services:
    php:
        container_name: ${APP_NAME}-php
        build:
            context: ..
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./../api:/var/www/api
            - ./.env:/var/www/api/.env
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        extra_hosts:
            - host.docker.internal:host-gateway

    database:
        container_name: ${APP_NAME}-db
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${APP_NAME}
            MYSQL_USER: ${APP_NAME}
            MYSQL_PASSWORD: ${APP_NAME}
            MYSQL_ROOT_PASSWORD: ${APP_NAME}
        volumes:
            - ./data/db:/var/lib/mysql
        ports:
            - '3306:3306'

    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:alpine
        restart: unless-stopped
        depends_on:
            - php
        environment:
            FASTCGI_HOST: ${APP_NAME}-php
            APP_NAME: ${APP_NAME}
            APP_PORT: ${APP_PORT}
            LISTEN_OPTIONS: ""
        volumes:
            - ./../api:/var/www/api
            - ./data/logs/nginx:/var/log/nginx
            - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
        ports:
            - ${APP_PORT}:${APP_PORT}
